### ISSUE TITLE
Persist the color used for sub populations as these items are selected

### ISSUE THREAD

**Issue by mmorper** [pr3d4t0r/COVIDvu#354] opened 2020-03-27 14:31 UTC
When you add or subtract a sub-population (states or countries) the color of the subpopulation changes.  It would be better if they were fixed (I thought Italy was flattening, but the color changed from orange to green and I was looking at china)

**Comment by kinabalu** [comment] 2020-03-27 15:18
duplicate of #296

**Comment by kinabalu** [comment] 2020-03-27 15:20
Duplicate of #296

**Closed as completed by kinabalu** 2020-03-27 15:20 UTC
